### ISSUE TITLE
Magnitude of Gradient is Bad : Inf While Training Polyglot Parser

### ISSUE THREAD

**Issue by Mounika2405** [irshadbhat/nsdp-cs#4]
Hi,
I tried running polyglot parser for 100 epochs but it seems like there is an exploding gradient problem after the 93rd epoch (ran on CPUs). Could you please help me resolve the issue?
<img width="567" alt="Screenshot 2020-01-16 at 6 53 08 PM" src="https://user-images.githubusercontent.com/33863436/72624399-e3d72380-396c-11ea-81dc-baf2da6c9076.png">

Thank you.

**Comment by irshadbhat** [comment]
This is more of a dynet issue than the parser error. [This dynet issue](https://github.com/clab/dynet/issues/1382) might be relevant.

You don't necessarily need to run the code for 100 iterations. The parser code starts saving model from the first epoch and dumps the model every time there is a new best on dev set. There should be a saved model. You can proceed your work with that.
